name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Setiap 6 jam
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Generate Snake GIF dan SVG
      - name: Generate Snake GIF and SVG
        uses: Platane/snk@master
        with:
          github_user_name: YanaMiku-BOTz
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Deploy ke GitHub Pages (output branch)
      - name: Push to GitHub Pages (output branch)
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
